// flow-typed signature: a05bd1b872769285c27770a19def421b
// flow-typed version: <<STUB>>/babel-plugin-import-7_v^1.6.7/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-import-7'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-import-7' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-import-7/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-import-7/lib/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-import-7/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-import-7/lib/index'>;
}
declare module 'babel-plugin-import-7/lib/Plugin.js' {
  declare module.exports: $Exports<'babel-plugin-import-7/lib/Plugin'>;
}
